### ISSUE TITLE
Thymeleaf generowanie templatki maila

### ISSUE THREAD

**Issue by pglg95** [PollubCafe/Flare-event-calendar#8]
Research i stworzenie templatki na potwierdzenie maila przy rejestracji i na potwierdzenie wzięcia udziału już po podjęciu przez organizatora decyzji o terminie

**Comment by marekpucek** [comment]
Zajmę się tym

**Comment by KosmalaJ** [comment]
Ja też XD

**Comment by Jarek0** [comment]
Od thymelife lepszy jest velocity
